name: Build & Publish
on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.event.repository.name }} #standard github.repository contains also the username
  APP_FOLDER: app
  TERRAFORM_FILES_PATH: infra


jobs:
  build:
    name: Application Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push ${{ env.IMAGE_NAME }} image
        uses: docker/build-push-action@v2
        with:
          context: "${{ env.APP_FOLDER }}/"
          push: true
          tags: ${{ secrets.AZ_ACR_ADDRESS }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.AZ_ACR_ADDRESS }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ secrets.AZ_ACR_ADDRESS }}/${{ env.IMAGE_NAME }}:buildcache,mode=max
          build-args: |
            GIT_SHA=${{ github.sha }}
            GIT_REF=${{ github.ref }}
            BUILD_ID=${{ github.run_id }}
            BUILD_NUMBER=${{ github.run_number }}

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}